services:
  web:
    image: nginx:1.23.3
    ports:
      - 8443:8443
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web/certbot/config/:/etc/letsencrypt/
    links:
      - frontend
      - api
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    command: npm run dev
    environment:
      NODE_ENV: development
      API_ROOT: https://api.localhost.letsrss.com:8443
      CODESPACE_NAME: ${CODESPACE_NAME}
    ports:
      - 8080:3000
    volumes:
      - ./frontend:/app
  api:
    build:
      context: api/
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    command: bash -c 'rm -f /tmp/server.pid && bundle exec rails s -b 0.0.0.0 -P /tmp/server.pid'
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    links:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      CODESPACE_NAME: ${CODESPACE_NAME}
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-db:/var/lib/postgresql/data
  job:
    build:
      context: api/
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
volumes:
  bundle:
  postgres-db:
  redis:
