import Head from 'next/head'
import getConfig from 'next/config'
const { serverRuntimeConfig, publicRuntimeConfig } = getConfig()
import { useState, useEffect } from 'react'
import { default as RssItem, RssItemType } from '@/components/rssItem'

export default function Home() {
    const [data, setData] = useState<any>(null)
    const [isLoading, setLoading] = useState(false)

    useEffect(() => {
        setLoading(true)
        fetch(`${publicRuntimeConfig.apiRoot}/reader/unread`)
            .then((res) => res.json())
            .then((data) => {
                setData(data)
                setLoading(false)
            })
    }, [])

    if (isLoading) return <p>Loading...</p>
    if (!data) return <p>No profile data</p>

    return (
        <>
            <Head>
                <title>Ultraladder</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="max-w-3xl mx-10">
                <div className="space-y-10">
                    {data.items.map((item: RssItemType) => (
                        <RssItem item={item} />
                    ))}
                </div>
            </main>
        </>
    )
}
