import Head from 'next/head'
import getConfig from 'next/config'
const { serverRuntimeConfig, publicRuntimeConfig } = getConfig()
import { useState, useEffect } from 'react'

export default function Home() {
    const [data, setData] = useState(null)
    const [isLoading, setLoading] = useState(false)

    useEffect(() => {
        setLoading(true)
        fetch(`${publicRuntimeConfig.apiRoot}/reader/unread`)
            .then((res) => res.json())
            .then((data) => {
                setData(data)
                setLoading(false)
            })
    }, [])

    if (isLoading) return <p>Loading...</p>
    if (!data) return <p>No profile data</p>

    return (
        <>
            <Head>
                <title>Ultraladder</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="max-w-3xl mx-10">
                <div className="space-y-10">
                    {data.items.map((item) => {
                        return (
                            <div>
                                <h2 className="font-bold">
                                    <a href={item.url} target="_blank">
                                        {item.title}
                                    </a>
                                </h2>
				       <div>                             <a href={item.url} target="_blank">
                                        {item.url}
                                    </a></div>
                                    <div>{item.published_at}</div>
                                <div className="flex space-x-4">
                                    {item.imageurl ? (
                                        <img
                                            src={item.imageurl}
                                            className="max-w-40 max-h-24"
                                        />
                                    ) : null}
                                    <div>{item.description}</div>
                                </div>
                            </div>
                        )
                    })}
                </div>
            </main>
        </>
    )
}
