require:
  - rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*.rb'
    - 'bin/**/*'
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 30
Style/Documentation:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
