# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0'
gem 'rails', '7.0.4'

gem 'bootsnap', require: false
gem 'pg'
gem 'puma'
gem 'rack-cors'
gem 'rss'
gem 'sidekiq'

group :development, :test do
  gem 'debug'
end

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
end
